from .world_mirror_v1 import NODE_CLASS_MAPPINGS as V1_MAPPINGS
from .world_mirror_v1 import NODE_DISPLAY_NAME_MAPPINGS as V1_DISPLAY_MAPPINGS
from .world_mirror_v2 import NODE_CLASS_MAPPINGS as V2_MAPPINGS
from .world_mirror_v2 import NODE_DISPLAY_NAME_MAPPINGS as V2_DISPLAY_MAPPINGS
from .panorama_mapper import NODE_CLASS_MAPPINGS as PANORAMA_MAPPER_MAPPINGS
from .panorama_mapper import NODE_DISPLAY_NAME_MAPPINGS as PANORAMA_MAPPER_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {**V1_MAPPINGS, **V2_MAPPINGS, **PANORAMA_MAPPER_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**V1_DISPLAY_MAPPINGS, **V2_DISPLAY_MAPPINGS, **PANORAMA_MAPPER_DISPLAY_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
