from .world_mirror_v1 import NODE_CLASS_MAPPINGS as V1_MAPPINGS
from .world_mirror_v1 import NODE_DISPLAY_NAME_MAPPINGS as V1_DISPLAY_MAPPINGS
from .world_mirror import NODE_CLASS_MAPPINGS as WORLD_MIRROR_MAPPINGS
from .world_mirror import NODE_DISPLAY_NAME_MAPPINGS as WORLD_MIRROR_DISPLAY_MAPPINGS
from .panorama_mapper import NODE_CLASS_MAPPINGS as PANORAMA_MAPPER_MAPPINGS
from .panorama_mapper import NODE_DISPLAY_NAME_MAPPINGS as PANORAMA_MAPPER_DISPLAY_MAPPINGS
from .world_stereo import NODE_CLASS_MAPPINGS as WS_MAPPINGS
from .world_stereo import NODE_DISPLAY_NAME_MAPPINGS as WS_DISPLAY_MAPPINGS
from .world_batching import NODE_CLASS_MAPPINGS as BATCH_MAPPINGS
from .world_batching import NODE_DISPLAY_NAME_MAPPINGS as BATCH_DISPLAY_MAPPINGS
from .cinematography import NODE_CLASS_MAPPINGS as CINEMA_MAPPINGS
from .cinematography import NODE_DISPLAY_NAME_MAPPINGS as CINEMA_DISPLAY_MAPPINGS
from .llm_environment_bridge import NODE_CLASS_MAPPINGS as BRIDGE_MAPPINGS
from .llm_environment_bridge import NODE_DISPLAY_NAME_MAPPINGS as BRIDGE_DISPLAY_MAPPINGS
from .per_scene_splats import NODE_CLASS_MAPPINGS as PSS_MAPPINGS
from .per_scene_splats import NODE_DISPLAY_NAME_MAPPINGS as PSS_DISPLAY_MAPPINGS
from .string_list_literal import NODE_CLASS_MAPPINGS as SLL_MAPPINGS
from .string_list_literal import NODE_DISPLAY_NAME_MAPPINGS as SLL_DISPLAY_MAPPINGS
from .render_output import NODE_CLASS_MAPPINGS as RO_MAPPINGS
from .render_output import NODE_DISPLAY_NAME_MAPPINGS as RO_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **V1_MAPPINGS,
    **WORLD_MIRROR_MAPPINGS,
    **PANORAMA_MAPPER_MAPPINGS,
    **WS_MAPPINGS,
    **BATCH_MAPPINGS,
    **CINEMA_MAPPINGS,
    **BRIDGE_MAPPINGS,
    **PSS_MAPPINGS,
    **SLL_MAPPINGS,
    **RO_MAPPINGS
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **V1_DISPLAY_MAPPINGS,
    **WORLD_MIRROR_DISPLAY_MAPPINGS,
    **PANORAMA_MAPPER_DISPLAY_MAPPINGS,
    **WS_DISPLAY_MAPPINGS,
    **BATCH_DISPLAY_MAPPINGS,
    **CINEMA_DISPLAY_MAPPINGS,
    **BRIDGE_DISPLAY_MAPPINGS,
    **PSS_DISPLAY_MAPPINGS,
    **SLL_DISPLAY_MAPPINGS,
    **RO_DISPLAY_MAPPINGS
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
